### ISSUE TITLE
rocksdb performance benchmark on gravition3, -march is better than -mcpu

### ISSUE THREAD

**Issue by xshen053** [aws/aws-graviton-getting-started#312] opened 2023-08-12 23:16 UTC
I took a look at some document and slides from aws and arm.
for example
https://d1.awsstatic.com/events/Summits/reinvent2022/CMP325_Coding-for-multiple-CPU-architectures-using-lessons-learned-in-HPC.pdf

<img width="904" alt="image" src="https://github.com/aws/aws-graviton-getting-started/assets/97472036/203395a9-dfeb-4046-ac6e-e6d19980053c">

So looks like if I know the cpu of my system, the performance is better if I use -mcpu instead of -march.

But I am testing rocksdb, and its default build includes `-march=armv8-a+crc+crypto`
and I changed it with `-mcpu=neoverse-512tvb+crc+crypto` which gives me worse number
# Results
## -march=armv8-a+crc+crypto
3896769 Op/s
## -mcpu=neoverse-512tvb+crc+crypto
<img width="252" alt="image" src="https://github.com/aws/aws-graviton-getting-started/assets/97472036/929dccf6-70cc-49de-a1b1-0a43c6c165ec">

# OS distribution and System Info
Ubuntu 20.04.6 LTS
<img width="740" alt="image" src="https://github.com/aws/aws-graviton-getting-started/assets/97472036/5d8c2e02-e5b8-4238-9451-10e3fd56a634">

# exact commands I used for testing rocksdb
## install phoronix-test-suite

`git clone https://github.com/phoronix-test-suite/phoronix-test-suite.git`
`sudo ./install-sh`
might need install other dependency like 
```
sudo apt install php7.4-cli
sudo apt-get install php-xml
```

## execute benchmark
`phoronix-test-suite benchmark rocksdb`

I am using 5, Read While Writing
<img width="481" alt="image" src="https://github.com/aws/aws-graviton-getting-started/assets/97472036/2681a150-0cd5-4435-8da2-b6dc837b301b">

Then just wait for the results

**Comment by xshen053** [comment] 2023-08-13 00:44
I detected it also uses -march=native which is `-march=armv8.4-a+crypto+sha3+sm4+sve+rng+ssbs+i8mm+bf16 ` on my instance. 

So I removed `-march=armv8-a+crc+crypto` and changed -march=native to `-mcpu=neoverse-512tvb+crypto+sha3+sm4+sve+rng+ssbs+i8mm+bf16` but still give me smaller number.

**Comment by sebpop** [comment] 2023-08-14 18:06
`-mpcu` is a combination of `-march` and `-mtune`.

In particular `-mtune` changes the default heuristics to generate hopefully better and faster code.  As with most "optimizations" passes in the compiler, there may be performance regressions due to side effects of "code transforms".

For example, when the compiler adds nops to align loops, the transform intent is to make the loop code faster, however in the same time the size of the code increases and may not fit in the instruction caches, which has a negative effect on performance.

**Comment by AWSjswinney** [comment] 2023-11-13 16:36
`-mcpu=neoverse-512tvb` does make some compromises between chips that fall into that category, so tuning may not be optimal for Graviton3 in some cases. In this case, you may want to use `-mcpu=native` for the improved tuning. I'm going to close this issue, but please do not hesitate to ask followup questions.

**Closed by AWSjswinney** 2023-11-13 16:36 UTC
